// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.9.2
// source: pb_proto/common/cs/cs.proto

package cs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_C2S_CREATE_CONTAINER_CMD  Command = 0 //创建容器cmd
	Command_S2C_CREATE_CONTAINER_CMD  Command = 1
	Command_C2S_STOP_CONTAINER_CMD    Command = 2 //关闭容器cmd
	Command_S2C_STOP_CONTAINER_CMD    Command = 3
	Command_C2S_RESTART_CONTAINER_CMD Command = 4 //重新启动容器cmd
	Command_S2C_RESTART_CONTAINER_CMD Command = 5
	Command_C2S_REMOVE_CONTAINER_CMD  Command = 6 //移除容器实例
	Command_S2C_REMOVE_CONTAINER_CMD  Command = 7
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "C2S_CREATE_CONTAINER_CMD",
		1: "S2C_CREATE_CONTAINER_CMD",
		2: "C2S_STOP_CONTAINER_CMD",
		3: "S2C_STOP_CONTAINER_CMD",
		4: "C2S_RESTART_CONTAINER_CMD",
		5: "S2C_RESTART_CONTAINER_CMD",
		6: "C2S_REMOVE_CONTAINER_CMD",
		7: "S2C_REMOVE_CONTAINER_CMD",
	}
	Command_value = map[string]int32{
		"C2S_CREATE_CONTAINER_CMD":  0,
		"S2C_CREATE_CONTAINER_CMD":  1,
		"C2S_STOP_CONTAINER_CMD":    2,
		"S2C_STOP_CONTAINER_CMD":    3,
		"C2S_RESTART_CONTAINER_CMD": 4,
		"S2C_RESTART_CONTAINER_CMD": 5,
		"C2S_REMOVE_CONTAINER_CMD":  6,
		"S2C_REMOVE_CONTAINER_CMD":  7,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_common_cs_cs_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_pb_proto_common_cs_cs_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{0}
}

type RET int32

const (
	RET_RET_OK                      RET = 0 //返回码正常
	RET_RET_ERROR                   RET = 1 //返回码异常
	RET_RET_CONTAINER_IS_EXIST      RET = 2 //容器实例存在
	RET_RET_START_CONTAINER_FAILD   RET = 3 //启动容器实例失败
	RET_RET_STOP_CONTAINER_FAILD    RET = 4 //关闭容器实例失败
	RET_RET_RESTART_CONTAINER_FAILD RET = 5 //重启容器实例失败
	RET_RET_REMOVE_CONTAINER_FAILD  RET = 6 //移除容器实例失败
)

// Enum value maps for RET.
var (
	RET_name = map[int32]string{
		0: "RET_OK",
		1: "RET_ERROR",
		2: "RET_CONTAINER_IS_EXIST",
		3: "RET_START_CONTAINER_FAILD",
		4: "RET_STOP_CONTAINER_FAILD",
		5: "RET_RESTART_CONTAINER_FAILD",
		6: "RET_REMOVE_CONTAINER_FAILD",
	}
	RET_value = map[string]int32{
		"RET_OK":                      0,
		"RET_ERROR":                   1,
		"RET_CONTAINER_IS_EXIST":      2,
		"RET_START_CONTAINER_FAILD":   3,
		"RET_STOP_CONTAINER_FAILD":    4,
		"RET_RESTART_CONTAINER_FAILD": 5,
		"RET_REMOVE_CONTAINER_FAILD":  6,
	}
)

func (x RET) Enum() *RET {
	p := new(RET)
	*p = x
	return p
}

func (x RET) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RET) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_proto_common_cs_cs_proto_enumTypes[1].Descriptor()
}

func (RET) Type() protoreflect.EnumType {
	return &file_pb_proto_common_cs_cs_proto_enumTypes[1]
}

func (x RET) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RET.Descriptor instead.
func (RET) EnumDescriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{1}
}

//基础消息结构
type BaseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd   uint32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Datas []byte `protobuf:"bytes,2,opt,name=datas,proto3" json:"datas,omitempty"`
}

func (x *BaseMsg) Reset() {
	*x = BaseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMsg) ProtoMessage() {}

func (x *BaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMsg.ProtoReflect.Descriptor instead.
func (*BaseMsg) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMsg) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *BaseMsg) GetDatas() []byte {
	if x != nil {
		return x.Datas
	}
	return nil
}

//基础回报消息
type BaseResponseMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd  uint32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Ret  uint32 `protobuf:"varint,2,opt,name=ret,proto3" json:"ret,omitempty"`
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *BaseResponseMsg) Reset() {
	*x = BaseResponseMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponseMsg) ProtoMessage() {}

func (x *BaseResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponseMsg.ProtoReflect.Descriptor instead.
func (*BaseResponseMsg) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResponseMsg) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *BaseResponseMsg) GetRet() uint32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *BaseResponseMsg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

//容器启动参数
type C2S_CreateContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryLimit  uint64 `protobuf:"varint,1,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`      //内存限制
	CpuCoreLimit uint32 `protobuf:"varint,2,opt,name=cpu_core_limit,json=cpuCoreLimit,proto3" json:"cpu_core_limit,omitempty"` //cpu限制
	Image        string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`                                      //启动镜像
	ImageName    string `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`             //启动容器名
}

func (x *C2S_CreateContainer) Reset() {
	*x = C2S_CreateContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_CreateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_CreateContainer) ProtoMessage() {}

func (x *C2S_CreateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_CreateContainer.ProtoReflect.Descriptor instead.
func (*C2S_CreateContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{2}
}

func (x *C2S_CreateContainer) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *C2S_CreateContainer) GetCpuCoreLimit() uint32 {
	if x != nil {
		return x.CpuCoreLimit
	}
	return 0
}

func (x *C2S_CreateContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *C2S_CreateContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type S2C_CreateContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId  string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` //启动容器实例id
	MemoryLimit  uint64 `protobuf:"varint,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuCoreLimit uint32 `protobuf:"varint,3,opt,name=cpu_core_limit,json=cpuCoreLimit,proto3" json:"cpu_core_limit,omitempty"`
	Image        string `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ImageName    string `protobuf:"bytes,5,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *S2C_CreateContainer) Reset() {
	*x = S2C_CreateContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_CreateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_CreateContainer) ProtoMessage() {}

func (x *S2C_CreateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_CreateContainer.ProtoReflect.Descriptor instead.
func (*S2C_CreateContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{3}
}

func (x *S2C_CreateContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *S2C_CreateContainer) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *S2C_CreateContainer) GetCpuCoreLimit() uint32 {
	if x != nil {
		return x.CpuCoreLimit
	}
	return 0
}

func (x *S2C_CreateContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *S2C_CreateContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

//关闭容器
type C2S_StopContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"` //关闭容器名称
}

func (x *C2S_StopContainer) Reset() {
	*x = C2S_StopContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_StopContainer) ProtoMessage() {}

func (x *C2S_StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_StopContainer.ProtoReflect.Descriptor instead.
func (*C2S_StopContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_StopContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type S2C_StopContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName   string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (x *S2C_StopContainer) Reset() {
	*x = S2C_StopContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_StopContainer) ProtoMessage() {}

func (x *S2C_StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_StopContainer.ProtoReflect.Descriptor instead.
func (*S2C_StopContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{5}
}

func (x *S2C_StopContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *S2C_StopContainer) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

//重新启动容器
type C2S_RestartContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"` //启动容器名称
}

func (x *C2S_RestartContainer) Reset() {
	*x = C2S_RestartContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RestartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RestartContainer) ProtoMessage() {}

func (x *C2S_RestartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RestartContainer.ProtoReflect.Descriptor instead.
func (*C2S_RestartContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_RestartContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type S2C_RestartContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *S2C_RestartContainer) Reset() {
	*x = S2C_RestartContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RestartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RestartContainer) ProtoMessage() {}

func (x *S2C_RestartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RestartContainer.ProtoReflect.Descriptor instead.
func (*S2C_RestartContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{7}
}

func (x *S2C_RestartContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

//移除容器实例
type C2S_RemoveContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"` //容器名称
}

func (x *C2S_RemoveContainer) Reset() {
	*x = C2S_RemoveContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RemoveContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RemoveContainer) ProtoMessage() {}

func (x *C2S_RemoveContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RemoveContainer.ProtoReflect.Descriptor instead.
func (*C2S_RemoveContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{8}
}

func (x *C2S_RemoveContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type S2C_RemoveContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *S2C_RemoveContainer) Reset() {
	*x = S2C_RemoveContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_common_cs_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RemoveContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RemoveContainer) ProtoMessage() {}

func (x *S2C_RemoveContainer) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_common_cs_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RemoveContainer.ProtoReflect.Descriptor instead.
func (*S2C_RemoveContainer) Descriptor() ([]byte, []int) {
	return file_pb_proto_common_cs_cs_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_RemoveContainer) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

var File_pb_proto_common_cs_cs_proto protoreflect.FileDescriptor

var file_pb_proto_common_cs_cs_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x62, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x63, 0x73, 0x2f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63,
	0x73, 0x22, 0x31, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x73, 0x22, 0x49, 0x0a, 0x0f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x93, 0x01, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x70,
	0x75, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x63, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x13, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x70, 0x75, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x70, 0x75,
	0x43, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x32,
	0x0a, 0x11, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x55, 0x0a, 0x11, 0x53, 0x32, 0x43, 0x5f, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x14, 0x43, 0x32, 0x53,
	0x5f, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x35, 0x0a, 0x14, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a, 0x13, 0x43, 0x32, 0x53, 0x5f, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x34, 0x0a,
	0x13, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x2a, 0xf7, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x1c, 0x0a, 0x18, 0x43, 0x32, 0x53, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a,
	0x18, 0x53, 0x32, 0x43, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54,
	0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x43,
	0x32, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45,
	0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x32, 0x43, 0x5f, 0x53,
	0x54, 0x4f, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d,
	0x44, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41,
	0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44,
	0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52,
	0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10,
	0x05, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x06, 0x12,
	0x1c, 0x0a, 0x18, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x07, 0x2a, 0xba, 0x01,
	0x0a, 0x03, 0x52, 0x45, 0x54, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x54, 0x5f, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01,
	0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45,
	0x52, 0x5f, 0x49, 0x53, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19,
	0x52, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49,
	0x4e, 0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x44, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18, 0x52,
	0x45, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45,
	0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x44, 0x10, 0x04, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x45, 0x54,
	0x5f, 0x52, 0x45, 0x53, 0x54, 0x41, 0x52, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e,
	0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x44, 0x10, 0x05, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45,
	0x54, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e,
	0x45, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x44, 0x10, 0x06, 0x32, 0x45, 0x0a, 0x14, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4d,
	0x67, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x0b, 0x2e,
	0x63, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x1a, 0x13, 0x2e, 0x63, 0x73, 0x2e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x73, 0x67, 0x22,
	0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_proto_common_cs_cs_proto_rawDescOnce sync.Once
	file_pb_proto_common_cs_cs_proto_rawDescData = file_pb_proto_common_cs_cs_proto_rawDesc
)

func file_pb_proto_common_cs_cs_proto_rawDescGZIP() []byte {
	file_pb_proto_common_cs_cs_proto_rawDescOnce.Do(func() {
		file_pb_proto_common_cs_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_common_cs_cs_proto_rawDescData)
	})
	return file_pb_proto_common_cs_cs_proto_rawDescData
}

var file_pb_proto_common_cs_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_proto_common_cs_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_proto_common_cs_cs_proto_goTypes = []interface{}{
	(Command)(0),                 // 0: cs.Command
	(RET)(0),                     // 1: cs.RET
	(*BaseMsg)(nil),              // 2: cs.BaseMsg
	(*BaseResponseMsg)(nil),      // 3: cs.BaseResponseMsg
	(*C2S_CreateContainer)(nil),  // 4: cs.C2S_CreateContainer
	(*S2C_CreateContainer)(nil),  // 5: cs.S2C_CreateContainer
	(*C2S_StopContainer)(nil),    // 6: cs.C2S_StopContainer
	(*S2C_StopContainer)(nil),    // 7: cs.S2C_StopContainer
	(*C2S_RestartContainer)(nil), // 8: cs.C2S_RestartContainer
	(*S2C_RestartContainer)(nil), // 9: cs.S2C_RestartContainer
	(*C2S_RemoveContainer)(nil),  // 10: cs.C2S_RemoveContainer
	(*S2C_RemoveContainer)(nil),  // 11: cs.S2C_RemoveContainer
}
var file_pb_proto_common_cs_cs_proto_depIdxs = []int32{
	2, // 0: cs.ContainerInstanceMgr.Execute:input_type -> cs.BaseMsg
	3, // 1: cs.ContainerInstanceMgr.Execute:output_type -> cs.BaseResponseMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_proto_common_cs_cs_proto_init() }
func file_pb_proto_common_cs_cs_proto_init() {
	if File_pb_proto_common_cs_cs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_common_cs_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResponseMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_CreateContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_CreateContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_StopContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_StopContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_RestartContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RestartContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_RemoveContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_common_cs_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RemoveContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_common_cs_cs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_proto_common_cs_cs_proto_goTypes,
		DependencyIndexes: file_pb_proto_common_cs_cs_proto_depIdxs,
		EnumInfos:         file_pb_proto_common_cs_cs_proto_enumTypes,
		MessageInfos:      file_pb_proto_common_cs_cs_proto_msgTypes,
	}.Build()
	File_pb_proto_common_cs_cs_proto = out.File
	file_pb_proto_common_cs_cs_proto_rawDesc = nil
	file_pb_proto_common_cs_cs_proto_goTypes = nil
	file_pb_proto_common_cs_cs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContainerInstanceMgrClient is the client API for ContainerInstanceMgr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContainerInstanceMgrClient interface {
	Execute(ctx context.Context, in *BaseMsg, opts ...grpc.CallOption) (*BaseResponseMsg, error)
}

type containerInstanceMgrClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerInstanceMgrClient(cc grpc.ClientConnInterface) ContainerInstanceMgrClient {
	return &containerInstanceMgrClient{cc}
}

func (c *containerInstanceMgrClient) Execute(ctx context.Context, in *BaseMsg, opts ...grpc.CallOption) (*BaseResponseMsg, error) {
	out := new(BaseResponseMsg)
	err := c.cc.Invoke(ctx, "/cs.ContainerInstanceMgr/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerInstanceMgrServer is the server API for ContainerInstanceMgr service.
type ContainerInstanceMgrServer interface {
	Execute(context.Context, *BaseMsg) (*BaseResponseMsg, error)
}

// UnimplementedContainerInstanceMgrServer can be embedded to have forward compatible implementations.
type UnimplementedContainerInstanceMgrServer struct {
}

func (*UnimplementedContainerInstanceMgrServer) Execute(context.Context, *BaseMsg) (*BaseResponseMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}

func RegisterContainerInstanceMgrServer(s *grpc.Server, srv ContainerInstanceMgrServer) {
	s.RegisterService(&_ContainerInstanceMgr_serviceDesc, srv)
}

func _ContainerInstanceMgr_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerInstanceMgrServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cs.ContainerInstanceMgr/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerInstanceMgrServer).Execute(ctx, req.(*BaseMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerInstanceMgr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cs.ContainerInstanceMgr",
	HandlerType: (*ContainerInstanceMgrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _ContainerInstanceMgr_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb_proto/common/cs/cs.proto",
}
